- hosts: nodes
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: true

  - name: Update all packages to the latest version
    apt:
      upgrade: dist
    become: true
