apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-read-only-binding 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-only-role 
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
