apiVersion: v1
kind: Service
metadata:
  name: influxdb-raid
  namespace: kube-system
spec:
  selector:
    app: influxdb-raid
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
---
apiVersion: v1
kind: Pod
metadata:
  name: influxdb 
  namespace: kube-system
  labels:
    app: influxdb-raid
spec:
  nodeName: node4
  containers:
  - name: influxdb 
    image: hypriot/rpi-influxdb 
    ports:
    - containerPort: 8086
    volumeMounts:
    - mountPath: /data
      name: raid-volume
  volumes:
  - name: raid-volume
    hostPath:
      path: /mnt/md0/influxdb 
      type: Directory
