apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus
  name: prometheus
  namespace: kube-system
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 30900
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus 
      containers:
      - name: prometheus
        image: brendanburns/armv7-prometheus:v2.2.1 
        args:
          - '--storage.tsdb.path=/data'
          - '--storage.tsdb.retention=3h'
          - '--config.file=/etc/prometheus/prometheus.yml'
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data 
        emptyDir: {}
